# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b328ffa353caa8b68e6c68bb68b90ca75b66384fb51ff2ffae288e5bd5e410ddd84e1cf843be6e79000cd409e7ce3a5c5b9dc246cc18fa38bfc9e5073701ab6

test:
  secret_key_base: b17d6771557094b0839caecad51b1f9fb77045969c62f9fb937a1698afd3d7862194c6b201e9d4824f57c3fd7d141947ba429eb76a582ef84cfd68a49712571b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
